### PR TITLE
Update to run with current OSIAM version

### PR DESCRIPTION
**Pull request by dacrome**

### CODE REVIEW

**Comment by dacrome** [comment]
In one test the [search result can not be deserialized](https://github.com/osiam/performance-tests/pull/8/files#diff-87702917fbe5fb34344bdfc6ddfe022aR43). Why?

**Comment by tkrille** [comment]
Please rebase

**Comment by tkrille** [comment]
Is the aforementioned test still failing?

**Comment by dacrome** [comment]
yes

**Comment by dacrome** [comment]
See https://circleci.com/gh/osiam/performance-tests/29

**Comment by tkrille** [comment]
Sorry but I cannot view the details of the CircleCI build. It's too much content.

**Comment by dacrome** [comment]
Just search for "Unable to deserialize search result" or "performance tests" under the unfolded "$ /bin/bash circle.sh (0)" content

**Comment by tkrille** [comment]
The JSON look right, dunno why it's failing.

**Comment by tkrille** [comment]
Thanks!

**Pull request merged**
